### ISSUE TITLE
新年快乐！求一份测试数据

### ISSUE THREAD

**Issue by bismarck22333** [jayoungo/SINS-GPS-Integrated-Navigation#11]
您好，希望您能提供一份测试数据，我的邮箱是763146926@qq.com，十分感谢！

**Comment by bismarck22333** [comment]
![image](https://user-images.githubusercontent.com/70585161/107232621-94263700-6a5c-11eb-85a2-19c2d356fcef.png)
您好，想问下这个Hc_0 是什么，十分感谢

**Comment by jayoungo** [comment]
@bismarck22333 已发送。
