### ISSUE TITLE
您好，我也想看看您的数据

### ISSUE THREAD

**Issue by kakusang2020** [jayoungo/SINS-GPS-Integrated-Navigation#12]
您好求一份IMU对准的数据，
M4_InitAlign中使用的，
我的邮箱是
xlgsang2020@gmail.com
请问您当时用的是MEMS吗？

**Comment by jayoungo** [comment]
@kakusang2020 已发送

**Comment by kakusang2020** [comment]
> @kakusang2020 已发送

多谢！
