### ISSUE TITLE
For M4_InitAlign simulation data

### ISSUE THREAD

**Issue by louishya14** [jayoungo/SINS-GPS-Integrated-Navigation#13]
Dear author,

Is it possible to give us the INS.txt and IMU.txt data for simulation using in M4_InitAlign?
Thank you a lot. And this is my e-mail: louishya14@gmail.com

**Comment by jayoungo** [comment]
@louishya14 Sent!

**Comment by louishya14** [comment]
Hi Jay,

Thank you a lot!
I will use it for simulation.

Best regards
Louis


Jay Young ***@***.***> 於 2021年6月4日 週五 下午2:34寫道：
