### ISSUE TITLE
亲爱的作者 

### ISSUE THREAD

**Issue by tu-oss** [jayoungo/SINS-GPS-Integrated-Navigation#14]
我也想使用一下您的数据 仿照您的程序 做一下实验 谢谢您的无私奉献 我的邮箱：1559808195@qq.com

**Comment by jayoungo** [comment]
@tu-oss Sent!

**Comment by jayoungo** [comment]
@LLLl-sys 已发。

**Comment by LLLl-sys** [comment]
Thanks!



---原始邮件---
发件人: "Jay ***@***.***&gt;
发送时间: 2022年4月22日(周五) 上午9:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jayoungo/SINS-GPS-Integrated-Navigation] 亲爱的作者  (#14)




 
@LLLl-sys 已发。

**Comment by hang-y-w** [comment]
Could you give me a copy of your raw data? yhlj911@163.com Thank you.
