### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mojingxi** [jayoungo/SINS-GPS-Integrated-Navigation#16]
Hello, when I was downloading and learning your code, I found that it could not run due to the lack of original data information. Could you please provide the original data? I can pay it, thank you very much!

**Comment by jayoungo** [comment]
@mojingxi Please give me an email, I can send you the data.

**Comment by mojingxi** [comment]
Hello,My email ***@***.*** you very much for your dedication-------- 原始邮件 --------发件人： Jay Young ***@***.***>日期： 2022年6月25日周六 14:46收件人： jayoungo/SINS-GPS-Integrated-Navigation ***@***.***>抄送： mojingxi ***@***.***>, Mention ***@***.***>主    题： Re: [jayoungo/SINS-GPS-Integrated-Navigation] help (Issue #16)
@mojingxi Please give me an email, I can send you the data.

**Comment by jayoungo** [comment]
Your email is masked.

**Comment by mojingxi** [comment]
Hello,my email is :xiaofengsmile0000@163.com.Thank you very much!

**Comment by jayoungo** [comment]
@mojingxi Sent!

**Comment by mojingxi** [comment]
thank you for your dedication
