### ISSUE TITLE
您好，请问能不能提供一些测试数据啊，非常感谢

### ISSUE THREAD

**Issue by qianCameron** [jayoungo/SINS-GPS-Integrated-Navigation#3]

**Comment by qianCameron** [comment]
您好，可以发我邮箱一份么973174834@qq.com 仅作自己学习使用，可以的话真的非常感谢！

**Comment by jayoungo** [comment]
@qianCameron 已发送

**Comment by qianCameron** [comment]
谢谢！


------------------ 原始邮件 ------------------
发件人: "Jay Young"<notifications@github.com>;
发送时间: 2019年4月16日(星期二) 下午3:49
收件人: "jayoungo/SINS-GPS-Integrated-Navigation"<SINS-GPS-Integrated-Navigation@noreply.github.com>;
抄送: "Cameron"<973174834@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [jayoungo/SINS-GPS-Integrated-Navigation] 您好，请问能不能提供一些测试数据啊，非常感谢 (#3)




@qianCameron 已发送
