### ISSUE TITLE
Do not have source data to run m-files correctly

### ISSUE THREAD

**Issue by molguitianzn** [jayoungo/SINS-GPS-Integrated-Navigation#6]
Hello, I admire your code! However I cannot run them correctly because I do not have the data you used. Could you please list your data sources on the readme file? Good luck!

**Comment by jayoungo** [comment]
@molguitianzn Please give me your e-mail address, I will send you the test data.

**Comment by molguitianzn** [comment]
3075526682@qq.com

**Comment by jayoungo** [comment]
@molguitianzn  Sent.
