### ISSUE TITLE
need data

### ISSUE THREAD

**Issue by FanZhenhui** [jayoungo/SINS-GPS-Integrated-Navigation#8]
Can you upload the Data?
Thanks very much!

**Comment by jayoungo** [comment]
@FanZhenhui Would you give me an e-mail address?

**Comment by 2624034705** [comment]
Would you send me the data if possible? 
this is my email: 2624034705@qq.com
extremely grateful

**Comment by jayoungo** [comment]
@2624034705 Sent!

**Comment by FanZhenhui** [comment]
1805608477@qq.com
Thank you very much!

**Comment by jayoungo** [comment]
@FanZhenhui Sent!

**Comment by FanZhenhui** [comment]
Thank you vvvvvvvery much!
